# Generated by Django 4.1 on 2023-03-17 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_comment_page_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelikes',
            name='liked_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_page', to='accounts.page'),
        ),
        migrations.AlterField(
            model_name='pagelikes',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
