# Generated by Django 4.1 on 2023-03-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pagelikes_liked_page_alter_pagelikes_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageelement',
            name='xCoord',
        ),
        migrations.RemoveField(
            model_name='imageelement',
            name='yCoord',
        ),
        migrations.AddField(
            model_name='imageelement',
            name='delete_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imageelement',
            name='display_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imageelement',
            name='image_large',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imageelement',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
