# Generated by Django 4.1 on 2023-03-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_imageelement_xcoord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageelement',
            old_name='display_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='imageelement',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='imageelement',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, default='https://i.ibb.co/V9G9x5p/e73a38fc9156.png', max_length=100)),
                ('delete_url', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
