# Generated by Django 4.1 on 2023-03-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_display_url_imageelement_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delete_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.CharField(blank=True, default='https://i.ibb.co/V9G9x5p/e73a38fc9156.png', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
