# Generated by Django 4.1 on 2023-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_delete_url_customuser_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='delete_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
